config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'dashboards#home'

  resource :physicians

  resource :patients

  resource :appointments, param: :id
  get '/appointments/edit/:id' => 'appointments#edit',as: :edit_appointment
  patch '/appointments/:id' => 'appointments#update',as: :update_appointment
  delete '/appointments/:id' => 'appointments#destroy',as: :delete_appointment
  get '/appointments/index' => 'appointments#index',as: :appointments_index
  get 'patient/appointments' => 'appointments#patient',as: :patient_appointments
  get 'physician/appointments' => 'appointments#physician',as: :physician_appointments

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :physician
  belongs_to :patient

  validates :patient_id, :physician_id, :appointment_date, :presence => :true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, :through => :appointments

  validates :name, :mobile_no, :presence => :true
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, :through => :appointments

  validates :name, :specialization, :presence => :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:edit, :update, :destroy]
  before_action :set_patients_and_physicians, only: [:new, :create, :edit]

  def new
    @appointment = Appointment.new
  end

  def create
    #TODO: Check Values

    @patient = Patient.find(params[:appointment][:patient])
    @physician = Physician.find(params[:appointment][:physician])
    @appointment = @patient.appointments.create(physician_id: params[:appointment][:physician],appointment_date: params[:appointment][:appointment_date])
    if @appointment.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    #TODO: change @edit_appointment
    if @appointment.update_attributes(appointment_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
    @todays_appointments = Appointment.all.select{|appointment| (appointment.appointment_date.to_date == Date.today)}
  end

  def destroy
    if @appointment.destroy
      redirect_to root_path
    end
  end

  def index
    @appointments = Appointment.all.order(appointment_date: :asc)
  end

  def patient
    if params[:search_term]
      @patient_appointments = Patient.find(params[:search_term]).appointments
    end
  end

  def physician
    if params[:search_term]
      @physician_appointments = Physician.find(params[:search_term]).appointments
    end
  end

  private
  def appointment_params
    params.require(:appointment).permit( :patient_id, :physician_id, :appointment_date)
  end

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def set_patients_and_physicians
    @patients = Patient.all
    @physicians = Physician.all
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def home
    @todays_appointments = Appointment.all.select{|appointment| (appointment.appointment_date.to_date == Date.today)}
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.create(patient_params)
    if @patient.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :mobile_no)
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  def new
    @physician = Physician.new
  end

  def create
    @physician = Physician.create(physician_params)
    if @physician.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def physician_params
    params.require(:physician).permit(:name, :specialization)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appointments/create.html.haml
%h1 Appointments#create
%p Find me in app/views/appointments/create.html.haml

app/views/appointments/destroy.html.haml
%h1 Appointments#destroy
%p Find me in app/views/appointments/destroy.html.haml

app/views/appointments/edit.html.haml
= form_for(@edit_appointment,url: update_appointment_path(@edit_appointment),method: 'patch',class:'form-horizontal form-center') do |f|
  = render 'shared/error',object: f.object
  = f.label("Patient Name:",class:'form-pad')
  = f.select "patient_id", @patients.collect{ |u| [u.name, u.id] },prompt: 'Select Patient', class:"form-control"
  %br
  = f.label("Physician Name:",class:'form-pad')
  = f.select "physician_id", @physicians.collect{ |u| [u.name, u.id] },prompt: 'Select Physician', class:"form-control"
  %br
  = f.label(:appointment_date, "Appointment Date:",class:'form-pad')
  %br
  = f.datetime_local_field(:appointment_date,class:"form-control")
  %br
  = f.submit("Edit appointment",class:"btn btn-primary")

-#
  = form_tag('/appointments',method: :patch,class:'form-horizontal form-center') do
    = label_tag("Patient Name:")
  = select_tag "patient", options_for_select(@patients.collect{ |u| [u.name, u.id] },'Select Patient'),class:"form-control"
  = label_tag("Physician Name:")
  = select_tag "physician", options_for_select(@physicians.collect{ |u| [u.name, u.id] },'Select Physician'),class:"form-control"
  = label_tag(:appointment_date, "Appointment Date:")
  = datetime_local_field_tag(:appointment_date,default: @edit_appointment.appointment_date, class:"form-control")
  %br
  = submit_tag("Make appointment",class:"btn btn-primary")

app/views/appointments/index.html.haml
%h2 Total Appointments : #{ @appointments.count}
%table.table.table-hover
  %tr
    %th Patient name
    %th Physician name
    %th Appointment Date
    %th Edit
    %th Delete
  - @appointments.each do |appointment|
    %tr
      %td= Patient.find(appointment.patient_id).name
      %td= Physician.find(appointment.physician_id).name
      %td= appointment.appointment_date
      %td= link_to 'Edit', edit_appointment_path(appointment)
      %td= link_to 'Delete',delete_appointment_path(appointment),method: 'delete'

app/views/appointments/new.html.haml
= form_for(@appointment,url: appointments_path,class:'form-horizontal form-center') do |f|
  = render 'shared/error',object: f.object
  = f.label("Patient Name:",class:'form-pad')
  = f.select "patient", @patients.collect{ |u| [u.name, u.id] },prompt: 'Select Patient', class:"form-control"
  %br
  = f.label("Physician Name:",class:'form-pad')
  = f.select "physician", @physicians.collect{ |u| [u.name, u.id] },prompt: 'Select Physician', class:"form-control"
  %br
  = f.label(:appointment_date, "Appointment Date:", class:'form-pad')
  %br
  = f.datetime_local_field(:appointment_date,class:"form-control")
  %br
  = f.submit("Make appointment",class:"btn btn-primary")

-#

  = form_tag(appointments_path,class:'form-horizontal form-center') do
    = label_tag("Patient Name:")
  = select_tag "patient", options_for_select(@patients.collect{ |u| [u.name, u.id] },'Select Patient'),class:"form-control"

  = label_tag("Physician Name:")
  = select_tag "physician", options_for_select(@physicians.collect{ |u| [u.name, u.id] },'Select Physician'),class:"form-control"
  = label_tag(:appointment_date, "Appointment Date:")
  %br
  = datetime_local_field_tag(:appointment_date,class:"form-control")
  %br
  = submit_tag("Make appointment",class:"btn btn-primary")

app/views/appointments/patient.html.haml
= form_tag patient_appointments_path,method: :get, class:'form-horizontal  form-center' do
  = label_tag(:search_term,"Patient Name:")
  = select_tag :search_term, options_for_select(Patient.all.collect{ |u| [u.name, u.id] },params[:search_term]),class:"form-control"
  = submit_tag("Search",class: 'btn btn-primary')
- if params[:search_term]
  %h2 Patient_appointments
  %table.table
    %tr
      %th Physician name
      %th Appointment Date
    - @patient_appointments.each do |appointment|
      %tr
        %td= Physician.find(appointment.physician_id).name
        %td= appointment.appointment_date

app/views/appointments/physician.html.haml
= form_tag physician_appointments_path,method: :get, class:'form-horizontal  form-center' do
  = label_tag(:search_term,"Physician Name:")
  = select_tag :search_term, options_for_select(Physician.all.collect{ |u| [u.name, u.id] },params[:search_term]),class:"form-control"
  = submit_tag("Search",class: 'btn btn-primary')
- if params[:search_term]
  %h2 Physician Appointments
  %table.table
    %tr
      %th Patient name
      %th Appointment Date
    - @physician_appointments.each do |appointment|
      %tr
        %td= Patient.find(appointment.patient_id).name
        %td= appointment.appointment_date

app/views/appointments/show.html.haml
%h2 Todays Appointments
%table.table.table-hover
  %tr
    %th Patient name
    %th Physician name
    %th Appointment Date
    %th Edit
    %th Delete
  - @todays_appointments.each do |appointment|
    %tr
      %td= Patient.find(appointment.patient_id).name
      %td= Physician.find(appointment.physician_id).name
      %td= appointment.appointment_date
      %td= link_to 'Edit', edit_appointment_path(appointment)
      %td= link_to 'Delete',delete_appointment_path(appointment),method: 'delete'

app/views/appointments/update.html.haml
%h1 Appointments#update
%p Find me in app/views/appointments/update.html.haml

app/views/dashboards/home.html.haml
.center
  = link_to 'Make an Appointment', new_appointments_path,class: "btn btn-warning btn-lg"
= render :template => 'appointments/show'

app/views/layouts/_footer.html.haml
%nav.navbar.navbar-default.navbar-fixed-bottom.navbar-inverse
  .copyright &copy;Copyrights Reserved

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
  .logo
    .title Hospital Appointment System
  %nav
    %ul.nav.navbar-nav.navbar-right.links-colour.rtop
      %li= link_to 'Home',root_path, class:"link-color"
      %li= link_to 'About',"#", class:"link-color"

app/views/layouts/_left.html.haml
%nav.left-main
  %ul.left-menu
    %li= link_to 'Home',root_path
    %li= link_to 'Add Physician', new_physicians_path
    %li= link_to 'Add Patient', new_patients_path
    %li= link_to 'Patient Appointments', patient_appointments_path
    %li= link_to 'Physician Appointments', physician_appointments_path
    %li= link_to 'All Appointments', appointments_index_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Hospital
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,600italic&subset=latin,latin-ext", :rel => "stylesheet", :type => "text/css"}
  %body
    = render 'layouts/header'
    .container-fluid
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message
      .row.main
        .left.col-xs-2
          = render 'layouts/left'
        .right.col-xs-10
          = yield
    = render 'layouts/footer'

app/views/patients/create.html.haml
%h1 Patients#create
%p Find me in app/views/patients/create.html.haml

app/views/patients/destroy.html.haml
%h1 Patients#destroy
%p Find me in app/views/patients/destroy.html.haml

app/views/patients/edit.html.haml
%h1 Patients#edit
%p Find me in app/views/patients/edit.html.haml

app/views/patients/new.html.haml
= form_for @patient, url: patients_path, class:'form-horizontal form-center' do |f|
  = render 'shared/error',object: f.object
  = f.label :name,"Patient Name"
  = f.text_field :name, class:'form-control'
  = f.label(:mobile_no, "Mobile Number:")
  = f.text_field :mobile_no, class:"form-control"
  %br
  = f.submit("Add Patient",class:"btn btn-primary")


-#
  = form_tag(patients_path,class:"form-horizontal form-center") do
    = label_tag(:name, "Patient Name:")
  = text_field_tag(:name,nil, class:"form-control")

  = label_tag(:mobile_no, "Mobile Number:")
  = telephone_field_tag(:mobile_no,nil,class:"form-control")
  %br
  = submit_tag("Add Patient",class:"btn btn-primary")

app/views/patients/update.html.haml
%h1 Patients#update
%p Find me in app/views/patients/update.html.haml

app/views/physicians/destroy.html.haml
%h1 Physicians#destroy
%p Find me in app/views/physicians/destroy.html.haml

app/views/physicians/edit.html.haml
%h1 Physicians#edit
%p Find me in app/views/physicians/edit.html.haml

app/views/physicians/new.html.haml
= form_for(@physician,url: physicians_path,class:"form-horizontal  form-center") do |f|
  = render 'shared/error',object: f.object
  = f.label(:name, "Physician Name:")
  = f.text_field :name, class:"form-control"
  = f.label(:specialization, "Specialization:")
  = f.text_field(:specialization, class:"form-control")
  %br
  = f.submit("Add Physician",class:"btn btn-primary")


-#
  = form_tag(physicians_path,class:"form-horizontal  form-center") do
    = label_tag(:name, "Physician Name:")
  = text_field_tag :name,nil , class:"form-control"
  = label_tag(:specialization, "Specialization:")
  = text_field_tag(:specialization,nil ,class:"form-control")
  %br
  = submit_tag("Add Physician",class:"btn btn-primary")

app/views/physicians/update.html.haml
%h1 Physicians#update
%p Find me in app/views/physicians/update.html.haml

app/views/shared/_error.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}
    %ul.alert
      - object.errors.full_messages.each do |msg|
        %li
          = msg